# Generated by Django 2.1.7 on 2019-02-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.CharField(max_length=255)),
                ('texto_encurtado', models.CharField(max_length=100)),
            ],
        ),
    ]
